"""The common part of message decoder/encoder.

Contains the identifiers of messages.

"""

CANT_EXECUTE_WORK_NOW_ANNOUNCEMENT =  1
COMMAND_DETERMINE_GRAPH_CYCLE_REQ  =  2
COMMAND_DETERMINE_GRAPH_CYCLE_RES  =  3
COMMAND_DETERMINE_WORK_CYCLE_REQ   =  4
COMMAND_DETERMINE_WORK_CYCLE_RES   =  5
COMMAND_ELECTION_REQ               =  6
COMMAND_ELECTION_RES               =  7
COMMAND_EXECUTE_GRAPH_REQ          =  8
COMMAND_EXECUTE_GRAPH_RES          =  9
COMMAND_EXECUTE_WORK_REQ           = 10
COMMAND_EXECUTE_WORK_RES           = 11
COMMAND_ORDER_WORK_EXECUTION_REQ   = 12
COMMAND_ORDER_WORK_EXECUTION_RES   = 13
HEARTBEAT_ANNOUNCEMENT             = 14
LOAD_GRAPH_AND_WORK_REQUEST        = 15
LOAD_GRAPH_AND_WORK_RESPONSE       = 16
LOAD_WORK_DETAILS_REQUEST          = 17
LOAD_WORK_DETAILS_RESPONSE         = 18
POKE_ANNOUNCEMENT                  = 19
PRESENT_YOURSELF_REQUEST           = 20
PRESENT_YOURSELF_RESPONSE          = 21
