"""The common part of message decoder/encoder.

Contains the identifiers of messages.

"""

COMMAND_WORK_EXECUTION_ANNOUNCEMENT =  1
DETERMINE_GRAPH_CYCLE_REQUEST       =  2
DETERMINE_GRAPH_CYCLE_RESPONSE      =  3
DETERMINE_WORK_CYCLE_REQUEST        =  4
DETERMINE_WORK_CYCLE_RESPONSE       =  5
EXECUTE_GRAPH_ANNOUNCEMENT          =  6
EXECUTE_WORK_ANNOUNCEMENT           =  7
HEARTBEAT_ANNOUNCEMENT              =  8
LOAD_GRAPH_AND_WORK_REQUEST         =  9
LOAD_GRAPH_AND_WORK_RESPONSE        = 10
LOAD_WORK_DETAILS_REQUEST           = 11
LOAD_WORK_DETAILS_RESPONSE          = 12
POKE_ANNOUNCEMENT                   = 13
PRESENT_YOURSELF_REQUEST            = 14
PRESENT_YOURSELF_RESPONSE           = 15
REPORT_FINISHED_WORK_ANNOUNCEMENT   = 16
